import { readFile, writeFile } from "node:fs/promises";

/**
 * Embeds the two brand fonts the `app/api/og/*` social cards render with, as
 * base64 so `next/og`'s `ImageResponse` can load them with no filesystem
 * read at request time — the deployed Cloudflare Worker has none. Regenerate
 * with `pnpm brand:og-fonts` after replacing either source file below.
 *
 * Only TrueType/OpenType (or WOFF1) bytes parse: the `next/og` vendored into
 * this Next.js build (satori's bundled `@shuding/opentype.js`) recognizes
 * only the `true`/`OTTO`/`wOFF` signatures and has no brotli decompressor,
 * so a WOFF2 buffer fails with "Unsupported OpenType signature wOF2" —
 * confirmed by constructing `ImageResponse` directly with each format, since
 * that is satori's own limit, not something this app's code can route
 * around. `assets/fonts/` only carries Barlow Condensed as `.woff2` (for
 * `next/font/local` in
 * app/layout.tsx, which decodes WOFF2 fine in a real browser), so
 * `barlow-condensed-700-latin.ttf` beside it is the same Google Fonts
 * release fetched once in TrueType form — this repo has no WOFF2→TTF
 * decoder to derive one from the other. Geist already ships a `.ttf` in
 * `node_modules/geist`, so it needs no extra copy.
 *
 * Only the wordmark weight (Bold/700) is embedded — the cards use it for
 * every display moment (wordmark, climber name, hero numbers), not the
 * in-app heading weight (Semibold/600) too, to keep the embedded set to the
 * two faces the brand voice actually distinguishes (display vs. body; see
 * `--font-display` in app/globals.css) rather than three weights for a
 * difference that barely reads at social-card scale.
 */
async function main() {
  const root = new URL("../", import.meta.url);
  const barlowCondensedBold = await readFile(
    new URL("assets/fonts/barlow-condensed-700-latin.ttf", root),
    "base64",
  );
  const geistMedium = await readFile(
    new URL("node_modules/geist/dist/fonts/geist-sans/Geist-Medium.ttf", root),
    "base64",
  );

  const banner =
    "// Generated by `pnpm brand:og-fonts` (scripts/generate-og-fonts.ts).\n" +
    "// Do not edit this file independently — edit the generator instead.\n";
  const body =
    `${banner}\n` +
    "/** Barlow Condensed Bold (700), TrueType — the wordmark/display voice. */\n" +
    `export const BARLOW_CONDENSED_BOLD_TTF_BASE64 = "${barlowCondensedBold}";\n\n` +
    "/** Geist Medium (500), TrueType — the supporting/body voice. */\n" +
    `export const GEIST_MEDIUM_TTF_BASE64 = "${geistMedium}";\n`;

  await writeFile(new URL("lib/og-fonts.generated.ts", root), body);
}

main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
